### PR TITLE
Don't use deprecated Laravel helper array_dot()

### PR DESCRIPTION
**Pull request by sburina**

### CODE REVIEW

**Comment by joshlewis** [comment]
Looks good to me! I think support for `array_dot()` was removed in Laravel 5.7. @creativeorange ?

**Comment by brainpink** [comment]
Hi @sburina,

Thanks for the pull request. We've created a new version: v1.0.12 which is available now.

Cheers!

**Comment by sburina** [comment]
Hi, @creativeorange,

Could you please update it on Packagist, the newest tag is still not visible?

Thanks a lot and keep up the good work! :)

**Comment by brainpink** [comment]
Done!

Verstuurd vanaf mijn iPhone

**Pull request merged**
